# Generated by Django 4.0.5 on 2024-10-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(max_length=10)),
                ('Name', models.TextField()),
                ('Desc', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
